pinecone init
NirantK/awesome-vectordb pull request #2
Opened 2023-05-08 12:14 UTC by adivik2000

This is the early script to upsert the first 10 rows of https://huggingface.co/datasets/Cohere/wikipedia-22-12-simple-embeddings/viewer/Cohere--wikipedia-22-12-simple-embeddings/train dataset and run a sample query based on the content to fetch top 3 results. 

Could you point me to the next steps?

You mentioned that we need an API endpoint to receive the query. What should the response be like?

2023-05-08 12:29 UTC, NirantK requested changes
In this PR, do the refactor to class, batching and the rest in the next PR please

2023-05-08 12:29 UTC, NirantK commented on pine_wiki.py
> +    pinecone.create_index(index_name, dimension=768, metric="euclidean")
cosine! Use cosine everywhere!

2023-05-08 12:29 UTC, NirantK commented on pine_wiki.py
> +index.upsert(vectors)
Can we do this in batches of 100 vectors? i.e. assume a longer dataset and and implement batching

2023-05-08 12:29 UTC, NirantK commented on pine_wiki.py
> +print(result)
Thanks for sharing the output, helpful! 

This should be wrapped into a FastAPI endpoint and separated from the upsert/insert. This is our `ask` endpoint. Implement some token based auth such that we don't have to store the token in our front end.

2023-05-08 12:29 UTC, NirantK commented on pine_wiki.py
> +dataset = load_dataset("Cohere/wikipedia-22-12-simple-embeddings", split="train")
To begin with, let's use the test during dev. It's smaller and will allow you to run this quickly several times. And during deployment make it easier to deploy.

2023-05-08 12:29 UTC, NirantK commented on pine_wiki.py
> +pinecone_indexes = pinecone.list_indexes()
Refactor this into an abstract `VectorDB` class. Implement a `Pinecone` class which inherits from `VectorDB` and implements the necessary functions. 

Then write a similar class for say Qdrant Cloud client.

2023-05-08 13:53 UTC, adivik2000 commented on pine_wiki.py
> +    pinecone.create_index(index_name, dimension=768, metric="euclidean")
This is done.

2023-05-08 13:57 UTC, adivik2000 commented on pine_wiki.py
> +pinecone_indexes = pinecone.list_indexes()
Did this. Please take a look?

2023-05-08 13:58 UTC, adivik2000 commented on pine_wiki.py
> +dataset = load_dataset("Cohere/wikipedia-22-12-simple-embeddings", split="train")
As this dataset has only train data, we're going with it.

2023-05-09 02:24 UTC, NirantK approved these changes

2023-05-09 02:24 UTC, merged